graph inserted in card
sameerddr/StockBoard pull request #8
Opened 2022-11-14 12:55 UTC by karthikgeek1

2022-11-14 15:34 UTC, Souvikdeb2612 requested changes

2022-11-14 15:34 UTC, Souvikdeb2612 commented on src/Components/Cards/Cards.jsx
> +const Cards = (props) => {
destructure props here

2022-11-14 15:34 UTC, Souvikdeb2612 commented on src/Components/Cards/Cards.jsx
> +import Graph3 from '../Graphs/Graph3';
1 line space before internal imports

2022-11-14 15:34 UTC, Souvikdeb2612 commented on src/Components/Graphs/Graph1.jsx
> +export const Graphdata1 = createContext()
create separate context folder

2022-11-14 15:34 UTC, Souvikdeb2612 commented on src/Components/Graphs/Graph2.jsx
> +export const Graphdata2 = createContext()
same as above

2022-11-14 15:34 UTC, Souvikdeb2612 commented on src/Components/Graphs/Graph3.jsx
> +export const Graphdata3 = createContext()
same as above

2022-11-14 15:34 UTC, Souvikdeb2612 commented on src/Components/Layout/StockLayout.jsx
>  import Cards from "../Cards/Cards";
1 line space before importing internal components

2022-11-15 15:09 UTC, karthikgeek1 commented on src/Components/Cards/Cards.jsx
> +const Cards = (props) => {
done sir

2022-11-15 15:10 UTC, karthikgeek1 commented on src/Components/Cards/Cards.jsx
> +import Graph3 from '../Graphs/Graph3';
done sir

2022-11-15 15:12 UTC, karthikgeek1 commented on src/Components/Graphs/Graph1.jsx
> +export const Graphdata1 = createContext()
done sir

2022-11-15 15:13 UTC, karthikgeek1 commented on src/Components/Graphs/Graph3.jsx
> +export const Graphdata3 = createContext()
done sir

2022-11-15 15:13 UTC, karthikgeek1 commented on src/Components/Layout/StockLayout.jsx
>  import Cards from "../Cards/Cards";
done sir

2022-11-15 17:06 UTC, Souvikdeb2612 approved these changes

2022-11-15 17:06 UTC, merged